### ISSUE TITLE
Browser: excList and incList should be removed from the browers state.

### ISSUE THREAD

**Issue by SteBry** [Software-Engineering-Bachelor-Project/mycroft#340]
The component should use the states com.filter.includedClips and com.filter.excludedClips for setting the default value of the checkboxes. 

When a checkbox is clicked these actions should be called:
- modifyFilter 
- getFilter 
- getClipsMatchingFilter 

Using the doActionsInOrder function, see Filter component for exampels

**Comment by sporreking** [comment]
#317 will take care of this problem
